SimSettings: Add manual SIM provisioning support
Author: Chaitanya Saggurthi <csaggurt@codeaurora.org>
Date:   Thu Jul 16 16:33:34 2015 +0530

    Telephony(MSIM): Add Manual provisioning support

    Add toggle switch UI option in SimSettings screen to
    enable/disable SIM cards

    Change-Id: Id07271aedb12eabc0b106ac278ba2e12c71cfe03

Author: Sandeep Gutta <sangutta@codeaurora.org>
Date:   Mon Aug 10 15:09:59 2015 +0530

    Telephony(MSIM): Manual provision related fixes

    - Consider Manual provision state while displaying
      active sub info list.
    - Enable sms/data user preference option only
    - Enable sms/data user preference option only
      if more than one subscription active.
    - Introduce below system proeprty to control AOSP
      behavior of user selection of fallback preference
      for sms/data
      "persist.radio.aosp_usr_pref_sel"

    Change-Id: I2b308b801f3f677c5a3ffaee5a8e6beda12aedd2

Author: Sandeep Gutta <sangutta@codeaurora.org>
Date:   Sun Sep 13 22:09:23 2015 +0530

    Telephony(MSIM): Fix to do not allow both SIM deactivation

    Use proper SubInfo record object to do not allow
    user to deactivate both SIMs on DSDS devices.

    Change-Id: I6f56d819367272b3a009c7a8133709c643e8bd84
    CRs-Fixed: 893504

Author: Sandeep Gutta <sangutta@codeaurora.org>
Date:   Mon Sep 14 20:14:07 2015 +0530

    Telephony(MSIM): Select preferred primary sub.

    Add UI to select preferred primary sub.
    It is used when two SIM cards inserted have same
    priority as per policy.

    Change-Id: I5726fe9f4df03e680dc2406854d08da77297444d

Author: Ricardo Cerqueira <ricardo@cyngn.com>
Date:   Thu Nov 5 18:23:52 2015 +0000

    Break MSIM dependency on qci-telephony-framework

    If the provisioning state is invalid, the framework is most likely
    absent. Consider the card as provisioned to pass all relevant checks.

    Change-Id: I975ff156e4328e9d3f6e2626a863bbacb29e3337

Author: LuK1337 <priv.luk@gmail.com>
Date:   Sun Jan 3 22:32:00 2016 +0100

    Hide manual provisioning switch when extphone framework is not present

    * It doesn't work without it.

    Change-Id: Iec11ec2006059f26668f2a6fee4c2c9ca6650119

Author: LuK1337 <priv.luk@gmail.com>
Date:   Sun Jul 3 22:11:26 2016 +0200

    Settings: Don't set the icon for sim activation / deactivation dialog

    * This icon doesn't look any good.
      It's better to just get rid of it.

    Change-Id: I47f70a80136695e9aa61ff98999a2cf770390079

Author: Luca Stefani <luca.stefani.ge1@gmail.com>
Date:   Sun Jul 3 21:56:08 2016 +0200

    Settings: Disable sim switch if subscription isn't valid

    Change-Id: I22ba9a3270da13f77fdd43586b7dc487f0929453

Author: Venkatraman Nerellapalli <venkataraman.nerellapalli@codeaurora.org>
Date:   Sat Jan 9 17:20:00 2016 +0530

    Telephony(MSIM): Fix ANR on SIM deactivation

    Dismiss dialog box on confirmation.
    SIM activation & deactivation in background thread.

    Change-Id: I0268a710f35e30b2abec3dd671942b52fc0e0b46
    CRs-Fixed: 957308

Author: Ricardo Cerqueira <ricardo@cyngn.com>
Date:   Thu Jul 28 12:29:40 2016 +0100

    SimSettings: Make provisioning optional even if qti-telephony is present

    Current code assumes the manual provisioning options should come
    up if the qti-telephony blob is present. Don't make that assumption.

    Change-Id: I5e4f28b628e3fe3fe9e506631e92c85103e87ccf

Author: Danny Baumann <dannybaumann@web.de>
Date:   Tue Feb 28 12:26:37 2017 +0100

    Clean up SIM enable toggle implementation

    - Move strings to cm_strings.xml
    - Improve string wording
    - Remove unused code
    - Streamline implementation

    Change-Id: I58fc3002cfcc37dd1798819223289cc541bed211

Author: Danny Baumann <dannybaumann@web.de>
Date:   Thu Feb 16 14:50:56 2017 +0100

    Fix possible NPE on SIM settings shutdown.

    Change-Id: Ibf6b54fc2b97a780cfd7ace17c54855ef7e70c57

Author: xyyx <xyyx@mail.ru>
Date:   Fri Jan 19 23:31:36 2018 +0800

    SimSettings: Correctly disable sim switch without SIM card

    * Code extracted from MM CAF

    Change-Id: I59924806302c57e5652b18235e50c9569153dbd3

Author: maxwen <max.weninger@gmail.com>
Date:   Sat Jan 20 13:39:17 2018 +0100

    SimSettings: Improve dialogs

    Squash of:

    Settings: no need to show a success alert dialog on sim switch

    very 'un-android-like' :)

    Change-Id: Ie68eed174464d7acf67171a509a19045e0d9c669

    Settings: fix neverending progress on sim activation change

    what a stupid bug....

    and while we are here - also the confirm dialog on
    deactivation is actually useless - using the switch
    should be more enough to not always ask and anoy user
    if he really knows what he is doing

    Change-Id: I38eb17cf8d12259f34b339da2ad807d12a5c0d41

Author: LuK1337 <priv.luk@gmail.com>
Date:   Fri Jan 26 18:39:50 2018 +0100

    SimSettings: Handle NoClassDefFoundError on devices without telephony-ext

    Change-Id: I9f4a2c773d8ad1d82993ea19bf9ee5e70e5d0516

Author: Bruno Martins <bgcngm@gmail.com>
Date:   Tue Jun 5 18:51:25 2018 +0100

    SimSettings: Use TelephonyExtUtils helper methods

     * TelephonyExtUtils class was recently added to Lineage SDK,
       thus allowing to clean up much of the code introduced
       for manual SIM provisioning.

    Change-Id: Id6eaffffb3c2b2b2dead36e0f56d8547e6188690

Author: Paul Keith <javelinanddart@gmail.com>
Date:   Wed Jun 27 01:00:02 2018 +0200

    Settings: Cleanup SimSettings additions

    * This shouldn't be an overlay, and is resulting in dead code

    Change-Id: I86bef790463ff5d40541f849f2d5e9fc1ae238c2

Issue: FP2P-242
Change-Id: I42e76651da449a6a82f95d6930384693cb04b26d